# arguments for dataset
dataset: dsifn
nclass: 2
crop_size: 128
data_root: /data/suyou/Codes/datasets/BIBR-DSIFN

# arguments for training
epochs: 80
batch_size: 16 # per GPU x 1 GPU
lr: 0.02
lr_multi: 1.0
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet50
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]

# <==== use PSPNet ====>
# model: pspnet
# backbone: resnet50
# replace_stride_with_dilation: [False, True, True]
